### ISSUE TITLE
No I2c slave mode support in wire.h

### ISSUE THREAD

**Issue by francisc0garcia** [01org/corelibs-arduino101#112]
the callbacks

> Wire.onReceive(receiveData);

and

> Wire.onRequest(sendData)

 are missing compare to previous versions. Now it is not possible to setup arduino 101 as slave to enable communications with other devices such as Raspberry or similar

Some overloads for method "begin" are also missing 

> error: no matching function for call to 'TwoWire::begin(int)'

**Comment by Dan-Emutex** [comment]
@francisc0garcia Arduino 101 does not support I2C Slave Mode at the hardware level - only Master Mode is supported.  That is why those callbacks are missing.

**Comment by francisc0garcia** [comment]
Thank you for explanation!

**Comment by rei-vilo** [comment]
Any plan to implement a software-based slave I²C on Arduino / Genuino 101?

**Comment by SidLeung** [comment]
We have examined the means to implement a software I2C.  However, it was determined that a follow on product with an actual hardware I2C interface made a lot more sense.

**Comment by Pachicito** [comment]
Why? Why is I2C slave not supported on the 101?

**Comment by SidLeung** [comment]
The I2C hardware interfaces originate from the ARC core (the processor used by the Arduino platform) of the Curie SoC only support Master mode.  Please refer to the Curie data sheet for more details.
