### ISSUE TITLE
setGyroOffset bug

### ISSUE THREAD

**Issue by dadez87** [01org/corelibs-arduino101#183]
I found a bug in "setGyroOffset" function.

`void CurieIMUClass::setGyroOffset(int axis, int offset)
{
    if (axis == X_AXIS) {
        setXGyroOffset(axis);
    } else if (axis == Y_AXIS) {
        setYGyroOffset(axis);
    } else if (axis == Z_AXIS) {
        setZGyroOffset(axis);
    }

    setGyroOffsetEnabled(true);
}`

Instead of "axis", "offset" should be written. Otherwise, the offset is set wrongly.
The same bug is also present in the "setAccelerometerOffset".
The bug can be solved as below (it is necessary also to cast int into int8_t).

`void CurieIMUClass::setAccelerometerOffset(int axis, int offset)
{
    if (axis == X_AXIS) {
        setXAccelOffset((int8_t)offset);
    } else if (axis == Y_AXIS) {
        setYAccelOffset((int8_t)offset);
    } else if (axis == Z_AXIS) {
        setZAccelOffset((int8_t)offset);
    }

    setAccelOffsetEnabled(true);
}`

**Comment by eriknyquist** [comment]
Hi @dadez87, if you look in https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieIMU/src/CurieIMU.cpp you'll see that these functions are using the 'offset' value. Perhaps you are looking at an old version?

**Comment by eriknyquist** [comment]
@dadez87 looking at the history I can see this was fixed in February
https://github.com/01org/corelibs-arduino101/commit/e8b8a5db546696735d5de38e58253b75cb411e7a

If you take the latest version from Github then you won't have this issue.

**Comment by kitsunami** [comment]
@eriknyquist, can you close this if it is fixed in current JSON releases?
