### ISSUE TITLE
Arduino101-specific #defines?

### ISSUE THREAD

**Issue by dantler** [01org/corelibs-arduino101#185]
I tried to port a library to Arduino101. This library was written for AVR and depended upon `<avr/interrupt.h>`, but I wanted to see if I could use `#ifdef` to swap in Arduino101-specific replacement routines.  I looked around but could not figure out which `#ifdef` to use!  I tried to export the cross-compiler's built-in #defines to see if I could detect the ARC architecture, but the export failed.

I ended up writing my own library which only works on Arduino101, but it still might be nice to use an `#ifdef` to warn users who aren't using Arduino101 that the library might not work.

Do you have a recommendation for an Arduino101-specific `#ifdef` that could be used for compatibility purposes?

**Comment by intel-larry** [comment]
Try:

#if defined(__ARDUINO_ARC__)

**Comment by dantler** [comment]
Thanks!  This works.  

In case anyone else looks at this, I found out that I could limit the scope of my Arduino library inside a [properties file](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification).  Arduino101 seems to use `arc32` as its architecture.
