### ISSUE TITLE
The PWM do not work when gyro is working 

### ISSUE THREAD

**Issue by vyuke** [01org/corelibs-arduino101#205]
hi, when i use an arduino101 to controlling LED by PWM via the internal IMU . i find PWM is not work,i could not figure it out ,could you help me?

**Comment by SidLeung** [comment]
Would you please provide the following info:

1. Are you using the software PWM (CurireTime1PWM) or the hardware PWM.
2. How do the two modules, IMU and PWM, interact with each other.
3. How do the modules work together for the goal of your project.

Thanks.

**Comment by eriknyquist** [comment]
@vyuke can you also provide the sketch, and give details about expected output vs. actual output, please.

**Comment by eriknyquist** [comment]
@vyuke ping. Any updates?

**Comment by eriknyquist** [comment]
@kitsunami recommend to close this in a week if still no response.
