### ISSUE TITLE
CurieBLE: advertise while connected to another device

### ISSUE THREAD

**Issue by q89123003** [01org/corelibs-arduino101#216]
In BLE protocal, it is possible for a BLE peripheral to advertise data while connected to another central device.
Is it possible to modify the CurieBLE to allow BLE peripheral to at least keep advertise device name while connected to another central device?
As I trace  BLEPeripheral.cpp, I found that the private function _startAdvertising will return in the beginning if the _state != BLE_PERIPH_STATE_READY, and the _state will be changed into BLE_PERIPH_STATE_CONNECTED after the device is connected. So is it possible to modify this part to allow BLE peripheral advertise while connected?

Thanks!

**Comment by SidLeung** [comment]
The reason for the Peripheral to stop advertising after a successful connection to a Central is to limit the connection to one Central at a time.  Not sure if, " allow[ing] BLE peripheral advertise while connected " is desirable.

**Comment by q89123003** [comment]
Thanks for your reply.
I understand the reason. But I mean in BLE peripheral should be able to advertise unconnectable data while connected to central. However, CurieBLE seems not yet implemented the function of advertising data, therefore I say "at least" advertise device name.

**Comment by SidLeung** [comment]
Please note that the Peripheral acts as if it has disappeared from the sense (going dark) once it is connected to a Central by stop advertising.  This will prevent other Centrals to discover it and attempt to connect.

**Comment by kitsunami** [comment]
Closing per Sidney's comment above.
