### ISSUE TITLE
platform.txt compiler.c.flags should contain -std=gnu11 to align with AVR core

### ISSUE THREAD

**Issue by eriknyquist** [01org/corelibs-arduino101#221]
This issue was brought to light by the following question;
https://github.com/01org/corelibs-arduino101/issues/220

**Comment by SidLeung** [comment]
Not sure if there is a requirement to make the Arduino 101 platform to align with the AVR core.  This may be a question for BaseCamp.

**Comment by intel-larry** [comment]
Yes it should behave the same.

Sent from my iPhone

On Jun 24, 2016, at 10:18 AM, SidLeung <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if there is a requirement to make the Arduino 101 platform to align with the AVR core. This may be a question for BaseCamp.

**Comment by jimdgit** [comment]
The whole idea is that code can move from one board to another with little or no change, so I would think it should be the same. (then boards like the MRK1000 move the led from 13 to 6)

**Comment by eriknyquist** [comment]
OK, I'll make this change today, and after I make sure all the examples still compile 
OK I'll make a pull request and link it here.

**Comment by eriknyquist** [comment]
PR #225 currently under review to address this.
