### ISSUE TITLE
Is there 6LoWPAN support?

### ISSUE THREAD

**Issue by echamberlain** [01org/corelibs-arduino101#263]
Hello,

Does the Arduino 101 support 6LoWPAN?

The [Zephyr Kernel 1.0.0 Release Notes](https://www.zephyrproject.org/content/zephyr-kernel-v100-release-notes) indicate that it possible with the hardware.

**Comment by eriknyquist** [comment]
Hi @echamberlain, Zephyr does support it, but there is no 6loWPAN hardware to drive on the Arduino 101 board; Zephyr is an independent project that support a variety of hardware.
