### ISSUE TITLE
Constant values to atan2 dont result in constant output

### ISSUE THREAD

**Issue by epic11** [01org/corelibs-arduino101#265]
I need to use the built in atan2 function, but even with constant input it sometimes gives me completely wrong values. Example from my Serial Monitor output:
1.51
1.51
1.51
1.51
1.51
1.51
86050.79
1.51
1.51
1.51
1.51
1.51
1.51
1.51

By printing:
Serial.println(atan2(454.00, 17206.00) * RAD_TO_DEG);

**Comment by PaulStoffregen** [comment]
Can you give us more info?  Think "reproducible", everything someone would need to recreate this problem.  Right now, we don't even know which board you're using, not to mention having a complete program to copy & paste into Arduino and upload to that board.

**Comment by epic11** [comment]
Sorry, for leaving such a short issue. I realized that this bug has something to do with handling interrupts in another part of my code, when I disable it atan works again, so it has probably something to do with my own code, I was just really confused by such a simple function not working.
