### ISSUE TITLE
[DOC] Reference/CurieIMUreadTemperature Wrong formula

### ISSUE THREAD

**Issue by GregorioW** [01org/corelibs-arduino101#270]
I’m aware that the following is not a crucial issue, but I hope it’s not a big deal to correct it (and that it’s the right place to report it).

In the [CurieIMU.readTemperature() reference](https://www.arduino.cc/en/Reference/CurieIMUreadTemperature) the conversion example is wrong.
Instead of
Celsius=(raw/32767.0)+23
it should be
`tempCelsius = rawTemperature / 512.0 + 23.0;`
(see [BMI60.cpp:2272](https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieIMU/src/BMI160.cpp#L2272))

**Comment by kitsunami** [comment]
@facchinm can you take a look at this and update the webpage if needed?

**Comment by facchinm** [comment]
Thanks for reporting, fixed :slightly_smiling_face:
