### ISSUE TITLE
[I2S] Curie_I2S Sample Rates are not tied to bit rate

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#307]
In [libraries/CurieI2S/src/CurieI2S.h](https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieI2S/src/CurieI2S.h), the 44.1 kHz sample rate constant is fixed for a 24-bit.

```
#define I2S_44K     0x000F000F
```

When using 16-bit, for example, `0x00160016` should be used.

**Comment by SidLeung** [comment]
Corrected in the re-factored version of CurieI2S library.
