### ISSUE TITLE
CurieBLE LED example error

### ISSUE THREAD

**Issue by darkwave** [01org/corelibs-arduino101#312]
LED example uses wrong class [BLECentralHelper instead of BLECentral](https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieBLE/examples/LED/LED.ino#L53)

**Comment by noelpaz** [comment]
The latest official release 1.0.7 still has the old class BLECentral. In the current tip of the master we implemented BLE Central functionality and now it is called BLECentralHelper. It is not a bug or error. The reason we had to do this is we wanted backward compatibility. The original CurieBLE implemented peripheral mode only but confusingly called the top class BLE Central.

The library is till undergoing changes and refactoring under Arduino's guidance so treat the current non official version as under development.  If you pull from the current master you will see that there will be more examples than the old library. Notice also where you can run a Central example and a recommended Peripheral example and will see transactions between the 2 boards. For example, LED and CallbackLED pair up with LEDCentral example sketch. We also mentioned that in the comments. Also note you will have to update the BLE Firmware and we have conveniently provided that upgrade mechanism as well from the IDE.

Yes your old sketches will need work if you want to use the current library. We did keep the old examples and should give you an idea what to change and the changes are very minimal.
