### ISSUE TITLE
I can NOT upload bootloader from 1.0.6 to 1.0.7

### ISSUE THREAD

**Issue by ouki-wang** [01org/corelibs-arduino101#321]
java.lang.NullPointerException
	at cc.arduino.packages.uploaders.SerialUploader.burnBootloader(SerialUploader.java:363)
	at processing.app.Editor.lambda$handleBurnBootloader$42(Editor.java:2752)
	at java.lang.Thread.run(Thread.java:745)
Error while burning bootloader.

**Comment by eriknyquist** [comment]
Did you try shutting down the IDE and opening it again?

**Comment by ouki-wang** [comment]
@eriknyquist 
yes，i does not work after open IDE again。i think that bat script's compatibility is not good

**Comment by calvinatintel** [comment]
Hi @ouki-wang, there were no firmware changes between 1.0.6 and 1.0.7. Why did you need to burn the bootloader?

**Comment by ouki-wang** [comment]
@calvinatintel ble_core image.bin is updated。

**Comment by calvinatintel** [comment]
BLE firmware shipped with 1.0.7 is the same as the factory version. The upcoming 2.0.0 release will change the BLE firmware, so we've shipped the factory version with 1.0.7 as a way to return to the original version. If you're seeing a message that you need to update the firmware, you can completely reset back to the factory version using the [Factory Recovery Flashpack](https://downloadcenter.intel.com/downloads/eula/25470/Arduino-101-software-package?httpDown=https%3A%2F%2Fdownloadmirror.intel.com%2F25470%2Feng%2Farduino101-factory_recovery-flashpack.tar.bz2) and try again. Please let us know how it went.
