### ISSUE TITLE
Serial.print() rounding error

### ISSUE THREAD

**Issue by DaisukeUra** [01org/corelibs-arduino101#339]
I think Serial.print() has an error about rounding.

Serial.print(0.95,1) should display "1.0" but real output is "0.0".
Serial.print(0.995,2) and Serial.print(0.9995,3) output "0.00" and "0.000" too.
They should output "1.000" and "1.0000".

**Comment by eriknyquist** [comment]
Hi @DaisukeUra, thanks for letting us know. I did actually fix this, see https://github.com/01org/corelibs-arduino101/commit/2e56b81a264c8760f095a12f650381b8ea8de831, we just haven't done a new release yet so you won't get the fix by downloading from the Boards Manager.
