### ISSUE TITLE
Software serial does not work in 1.07

### ISSUE THREAD

**Issue by ilanganor** [01org/corelibs-arduino101#354]
software serial does not work properly in version 1.07

when connecting it to an actual device it returns "garbage"

the latest working version for the software serial is v1.04

reverting to 1.04 solved the issue

**Comment by bigdinotech** [comment]
@ilanganor would you happen to have a scope capture of it failing?
Also what baud rate are you using when it fails. Or even better are you able to share your sketch that SoftwareSerial fails?

**Comment by ilanganor** [comment]
Hello 
I do not have a scope capture of the signals.

I am working at 4800 baud rate and this sketch works great with version 1.04, however fails with versions 1.05, 1.06 and 1.07 

I also noticed I am not the only one with that problem:

[](https://forum.arduino.cc/index.php?topic=430581.0)


here is my test sketch:

[modem_At.txt](https://github.com/01org/corelibs-arduino101/files/644248/modem_At.txt)

**Comment by paultanner** [comment]
Also failing when I use 1.04 (softwareSerial on pins 3 and 4).
Do these pins support softwareSerial?

**Comment by kitsunami** [comment]
@bigdinotech , can you list the speeds that are supported?

**Comment by bigdinotech** [comment]
fixed by
https://github.com/01org/corelibs-arduino101/commit/c794c47abf9864af34b768f46f0792991f12a649
