### ISSUE TITLE
CurieBLE: BLE.scan() should scan with duplicate filter

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#368]
In https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieBLE/examples/central/scan/scan.ino

```arduino
BLE.scan();
```

scans without filter, however I expect it to scan with a duplicate filter.

**Comment by SidLeung** [comment]
Track by Jira 802

**Comment by kitsunami** [comment]
Addressed by #457

**Comment by sandeepmistry** [comment]
This is a bit better with the 2.0.1 RC1 release, however the logic to enable the duplicate filtering is inverted.

I've submitted PR #476 to address this.

**Comment by SidLeung** [comment]
Please note that PR #476 is superseded by the follow PR,

https://jira.ndg.intel.com/browse/ATLEDGE-896

**Comment by sandeepmistry** [comment]
This looks good now with the 2.0.2 RC JSON @SidLeung provided me. Closing

The scan.ino example only reports discovered peripherals once as expected and the scan_callback.ino example reports every advertisement.

However, as @SidLeung mentioned `BLE.scan()` does not report the scan response as I expected. I'll open a separate issue to discuss this.
