### ISSUE TITLE
CurieBLE: BLE.scan(...) allways scans without duplicate filter

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#369]
In https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieBLE/examples/central/scan/scan.ino:

If I change the `BLE.scan();` line to either `BLE.scan(true);` or `BLE.scan(false);` all scan without duplicates. I expect it to only receive peripheral per Bluetooth address with the duplicate filter enabled.

**Comment by SidLeung** [comment]
This issue is logged as Jira 802.

@sandeepmistry I think touch on this topic before.  The latest Nordic stack does not have readily available support for duplicate filtering.  Will investigating this issue further.

**Comment by sandeepmistry** [comment]
Ok, if this is not supported by the Nordic soft device stack, the current API's are very confusing and we need to change them.

**Comment by kitsunami** [comment]
Addressed by #457

**Comment by sandeepmistry** [comment]
I've tested this with the 2.0.1 RC1 release, now a duplicate filter is present. Closing.
