### ISSUE TITLE
CurieBLE: cannot discover advertised 128-bit service of bleno

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#372]
Similar to #371 but I'm using [bleno](https://github.com/sandeepmistry/bleno) to advertise a 128-bit UUID ([test.js](https://github.com/sandeepmistry/bleno/blob/master/test.js)).

The scan example doesn't display the 128-bit UUID (which is in the advertisement data), however LightBlue on iOS does display the advertised 128-bit UUID.

**Comment by SidLeung** [comment]
Logged as part of Jira 792 and under internal review.

**Comment by kitsunami** [comment]
Addressed by #450

**Comment by sandeepmistry** [comment]
I've tested this with the v2.0.1 RC1 release, and I see the correct behaviour. Closing.
