### ISSUE TITLE
CurieBLE: BLE.scanForAddress(...) API is not present

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#376]
I wanted to update the SensorTag button example to match the API we discussed in November, however the `BLE.scanForAddress(...)` is not present.

**Comment by SidLeung** [comment]
This issue is logged as Jira 797.

**Comment by SidLeung** [comment]
Resolution has been approved, tested, and merged to main trunk.  Will be in the next nightly build JSON.

**Comment by SidLeung** [comment]
@sandeepmistry , resolution is available in nightly build starting on 2/9/2017,

http://mkfs.ndg.intel.com/json/public/package_public-07.4_index.json

**Comment by sandeepmistry** [comment]
This looks good, the API is in the JSON @SidLeung provided and works.
