### ISSUE TITLE
CurieTimerOne: PWM on two channels/pins

### ISSUE THREAD

**Issue by murikill** [01org/corelibs-arduino101#424]
How can I use two PWM channels with CurieTimeOne library with the same frequency? 

Thanks in advance

**Comment by eriknyquist** [comment]
Hi @murikill, we do our best to discuss only software defects & feature requests in the Issue Tracker here.

If you have questions about how to use the library, there is a nice community forum here which a lot of people use: https://forum.arduino.cc/index.php?board=103.0

**Comment by murikill** [comment]
Thanks for reply. The question was exactly IF is possible to use the library with two independent timers.
