### ISSUE TITLE
CurieBLE: Deprecated BLEConnected and BLEDisconnected events not triggered

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#445]
While testing the v1.0.7 LED callback example (https://github.com/01org/corelibs-arduino101/blob/1.0.7/libraries/CurieBLE/examples/CallbackLED/CallbackLED.ino), I noticed the BLEConnected and BLEDisconnected events are not being trigged.

**Comment by sgbihu** [comment]
Fixed

**Comment by SidLeung** [comment]
This issue is tracked by Jira ticket 858.

**Comment by russmcinnis** [comment]
Confirmed that this is working with PR447 using the sketch linked here. Also ran basic BAT tests along with some manual testing.

**Comment by russmcinnis** [comment]
this works with PR 455 system tests and tested for seeing connects and disconnects. Looks good.

**Comment by sandeepmistry** [comment]
Tested again with the 2.0.1 RC1 release, this now works as expected. Closing.

```
Connected event, central: AC:BC:32:7C:FA:26
Characteristic event, written: LED on
Characteristic event, written: LED off
Disconnected event, central: AC:BC:32:7C:FA:26
```
