### ISSUE TITLE
LED not cleared after loading a blank sketch

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#473]
This occurred while testing with the 2.0.1 rc1 JSON.

1) Load sketch to turn LED on:

```arduino
void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, HIGH);
}

void loop() {
}
```

2) LED is on.

3) Load blank sketch:

```arduino
void setup() {
}

void loop() {
}
```

4) LED remains on.

After step 3) I expect the LED to be off as the sketch is empty.

**Comment by bigdinotech** [comment]
@sandeepmistry I was able to reproduce but only if extend the delay for when the pin state is HIGH.
Basically its just keeping the state it was at before it was rebooted.
I should have a fix soon.

**Comment by SidLeung** [comment]
Tracked by Jira 892.

**Comment by sandeepmistry** [comment]
This looks good now with the 2.0.2 RC JSON @SidLeung provided me. Closing.
