### ISSUE TITLE
Pins should default to input mode on sketch start

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#486]
To keep track of the initial discussion from https://github.com/01org/corelibs-arduino101/pull/483#issuecomment-287908181

Are all the pins in input mode on sketch start? That's the default behaviour of AVR boards like the Uno and we should aim for the same for the 101.

For example, the SAMD core for boards like the Zero and MKR1000 has the following:

```c
  // Setup all pins (digital and analog) in INPUT mode (default is nothing)
  for (uint32_t ul = 0 ; ul < NUM_DIGITAL_PINS ; ul++ )
  {
    pinMode( ul, INPUT ) ;
  }
```

https://github.com/arduino/ArduinoCore-samd/blob/96745cd48d8232ed37ec03d3a71d510aa9410f38/cores/arduino/wiring.c#L83-L87

cc/ @cmaglie

**Comment by bigdinotech** [comment]
https://github.com/01org/corelibs-arduino101/commit/6b33e736a7ba9c5038c1a14fb7e6fb5bc099be71
