### ISSUE TITLE
CurieBLE: SensorTag example no longer works out of the box

### ISSUE THREAD

**Issue by sandeepmistry** [01org/corelibs-arduino101#497]
As discussed in https://github.com/01org/corelibs-arduino101/issues/370#issuecomment-289112547 when `BLE.scan()` is called no scan response is processed currently.

This causes the `central/sensortag_button.ino` example to not work as it checks the local name of peripherals and the SensorTag puts on the local name in the scan response.

Maybe we need a short term fix to the example?

**Comment by russmcinnis** [comment]
this feature appears to work with PR500 (tested with PR475 + PR500)

**Comment by sandeepmistry** [comment]
This is working for me now with the 2.0.1-rc2.1 JSON @yashaswini-hanji provided us.
