### ISSUE TITLE
Define functional requirements for BLE.scan() to process duplicated Peripherals.

### ISSUE THREAD

**Issue by SidLeung** [01org/corelibs-arduino101#508]
The BLE.scan API is (in v 2.0.2) capable of filtering out duplicated detected Peripherals.  The fact that Advertisement data of a Peripheral may be presented in one or multiple packets (Adv Data and Scan Response Data).  Thus, this ticket is to clarify the requirements of the scan() API on how to process the Adv info from different kinds of Peripheral.

**Comment by SidLeung** [comment]
Capturing a discussion on this issue here,

https://github.com/01org/corelibs-arduino101/pull/500#discussion_r108316928

**Comment by SidLeung** [comment]
@sandeepmistry @sgbihu , please present your suggestions/requests for change here.

**Comment by sgbihu** [comment]
The scan request will send out after the central see the advertising. So the scan response will be got in an expected time. The implementation can add a delay to return new device. I have implement a solution here https://github.com/01org/corelibs-arduino101/pull/502

**Comment by novashah** [comment]
Fixed and Merged.
