### ISSUE TITLE
udev rules

### ISSUE THREAD

**Issue by agdl** [01org/corelibs-arduino101#512]
On the Arduino [GS page](https://www.arduino.cc/en/guide/arduino101) we have:

```
Linux only: some distributions need to be configured to 
perform the upload. After installing the core, execute 
sudo ~/.arduino15/packages/Intel/tools/arduino101load/1.6.4+1.18/scripts/create_dfu_udev_rule 
inside a shell to gain upload permissions. 
``` 

anyway in the new core release the /scripts path seems to not exist

**Comment by agdl** [comment]
I'm using the 2.0.1 RC2.1 JSON on ubuntu

**Comment by sandeepmistry** [comment]
cc/ @facchinm

**Comment by facchinm** [comment]
Correct, the rules were part of the `arduino101loader` package. I'm for moving them into the core; could it be a solution?
