### ISSUE TITLE
Serial output data will be stuck

### ISSUE THREAD

**Issue by coloz** [01org/corelibs-arduino101#537]
Run the example Gyro,serial output data will be stuck.
Time is uncertain, but after a while will be stuck

**Comment by SidLeung** [comment]
Please specify if you were using a pre-release version of the Corelibs that you take from a Pull Request here.

**Comment by coloz** [comment]
version 2.0.2
example CurieIMU>Gryo
I tried to replace the usb cable, replace other 101 board, replace the PC\Mac, the problem still exists

**Comment by eriknyquist** [comment]
Try this fix
https://github.com/01org/corelibs-arduino101/pull/540
