### ISSUE TITLE
BMI160 setTapDetectionThreshold typo

### ISSUE THREAD

**Issue by abelsm2** [01org/corelibs-arduino101#539]
In line 821 of CurieIMU.cpp
```
            bmiThreshold = (threshold - 2500) / 500.0;
```

I believe the 2500 should be 250 instead.

https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieIMU/src/CurieIMU.cpp#L821

**Comment by bigdinotech** [comment]
resolved with 6d3c39d3f36807bf02ef1fc01cdc31395d31a3b8
