### ISSUE TITLE
txPin and rxPin are defined as global variables in SoftwareSerial.cpp

### ISSUE THREAD

**Issue by soundanalogous** [01org/corelibs-arduino101#89]
Because the variables `txPin` and `rxPin` are defined as global variables in SoftwareSerial.cpp (`/CurieSoftwareSerial/SoftwareSerial.cpp`) they cannot be used in sketches. This is going to break a lot of existing sketches since they are commonly used variable names in sketches. Please make these variables private or prepend an underscore (`_txPin`) or make them more specific (`curieSwSerialTXPin`) or other convention to differentiate.

**Comment by soundanalogous** [comment]
Looks like `txPin` is no longer defined globally but `rxPin` still is: https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieSoftwareSerial/SoftwareSerial.cpp#L49

**Comment by soundanalogous** [comment]
Also, I don't see any reason why `rxPin` can't be defined as a private property in SoftwareSerial.h because it is not ever used in the global scope. All use is within methods.

**Comment by rwaldron** [comment]
> defined as global variables in SoftwareSerial.cpp 

I'd go further and require that this implementation must only expose those identifiers that the [SoftwareSerial](https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/libraries/SoftwareSerial) exposes.

**Comment by kitsunami** [comment]
Please review. If not fixed, assign to Sidney.

**Comment by soundanalogous** [comment]
It was fixed: https://github.com/01org/corelibs-arduino101/pull/101#issuecomment-173016516.

**Comment by jgithubs** [comment]
Verified as fixed on 2/8/16
