### ISSUE TITLE
Functions "*.disconnect()" and "*.end()" doesn't work

### ISSUE THREAD

**Issue by mwms** [01org/corelibs-arduino101#97]
example
ble_peripheral.end()
central.disconnect()

**Comment by kitsunami** [comment]
To Sidney, to be worked on with JIRA 544.

**Comment by SidLeung** [comment]
Please note that the current Arduino platform can only be a Peripheral, no Central features are available.  If you are trying to finding out if your board is still connected to the host, you can use the method, BLECentral::connected().

**Comment by sandeepmistry** [comment]
@SidLeung I looked into this a few months ago, the issue is ```central.disconnect()``` does not trigger a disconnection of the connected central. From what I remember the handle book keeping in `CurieBLE` looked ok, I suspect there is something wrong on the nRF51 f/w side or incorrect messaging format.

**Comment by SidLeung** [comment]
@sandeepmistry Thanks for the info.  Will track that down,

**Comment by ccoulton** [comment]
Related Question, is there a way to start advertising with an interrupt? end seems to work when not connected to a central, but restarting the perhipheral seems impossiable.

**Comment by eriknyquist** [comment]
@SidLeung any idea if this has been fixed in the recent BLE merge?

**Comment by noelpaz** [comment]
I verified that disconnect and end works from a peripheral using the API disconnect and end for the current CurieBLE implemented by @sgbihu  (Liang's team) . I am closing this.


Thanks
